
if(typeof Widgets=="undefined"){Widgets={};}
Widgets.EditInPlace=Class.create();Widgets.EditInPlace.currentEditElement={};Widgets.EditInPlace.elements=[];Widgets.EditInPlace.li=null;Widgets.EditInPlace.prototype={initialize:function(id,pk,_3){this.id=id;this.pk=pk;this.options=_3;Widgets.EditInPlace.currentEditElement[this.id]="";var _4=new Kore.JSLoader();_4.addFile("includes/yui/yahoo/yahoo.js");_4.addFile("includes/yui/dom/dom.js");_4.addFile("includes/yui/event/event.js");_4.addFile("includes/yui/animation/animation.js");_4.addFile("includes/yui/connection/connection.js");_4.addFile("includes/kore/js/error.js");_4.addFile("includes/kore/js/browser/browser.js");_4.addFile("includes/kore/js/dataprovider/transporter.js");_4.addFile("includes/kore/js/dataprovider/dataprovider.js");_4.addFile("includes/kore/js/dataprovider/jsonprovider.js");_4.addFile("includes/kore/js/loadingindicator/loadingindicator.js");try{_4.loadFiles(function(){if(!Kore.isOkForAjax()){return false;}
var _5=new Kore.CSSLoader();_5.addFile("includes/jaxon/css/loading.css");_5.loadFiles(function(){Kore.addUnloadListener(this.unload,this);this.initializeEditInPlace();}.bind(this));}.bind(this));delete _4;}
catch(e){}},unload:function(){Widgets.EditInPlace.elements=[];},initializeEditInPlace:function(){Widgets.EditInPlace.li=Kore.LoadingIndicator.create();var _6=YAHOO.util.Dom.get("editinplace_"+this.id+"_"+this.pk);YAHOO.util.Event.addListener(_6,"mouseover",function(){this.showAsEditable(_6,true);}.bind(this),this,true);YAHOO.util.Event.addListener(_6,"mouseout",function(){this.showAsEditable(_6,false);}.bind(this),this,true);YAHOO.util.Event.addListener(_6,"click",function(){this.changeToEditable(_6);}.bind(this),this,true);},showAsEditable:function(_7,_8){if(!_8){YAHOO.util.Dom.removeClass(_7,"over_edittext");}else{YAHOO.util.Dom.addClass(_7,"over_edittext");if(this.options.click!=""){_7.title=this.options.click;}}},changeToEditable:function(_9){if(Widgets.EditInPlace.currentEditElement[this.id]==_9.id){return;}
if(Widgets.EditInPlace.currentEditElement[this.id]!=""){this.cleanup(Widgets.EditInPlace.currentEditElement[this.id]);}
Widgets.EditInPlace.currentEditElement[this.id]=_9.id;_9.style.display="none";var _a=_9.innerHTML;if(_a.toLowerCase()==this.options.empty.toLowerCase()){_a="";}
var _b="<textarea id=\""+_9.id+"_textarea\" class=\"editable_textarea\"></textarea>";var _c="<div><a href=\"#\" id=\""+_9.id+"_save\" class=\"editlink\">"+this.options.save+"</a> <a href=\"#\" id=\""+_9.id+"_cancel\" class=\"editlink\">"+this.options.cancel+"</a></div>";var el=document.createElement("div");el.id=_9.id+"_editor";el.innerHTML=_b+_c;_9.parentNode.insertBefore(el,_9);YAHOO.util.Dom.get(_9.id+"_textarea").value=_a;var _e=el.firstChild;_e.focus();if(Kore.is.ie){var _f=_e.createTextRange();_f.collapse(false);_f.select();}else{if(Kore.is.mozilla){_e.setSelectionRange(_e.value.length,_e.value.length);}}
var _10=YAHOO.util.Dom.get(_9.id+"_save");var _11=YAHOO.util.Dom.get(_9.id+"_cancel");YAHOO.util.Event.addListener(_10,"click",this.updateValue,this,true);YAHOO.util.Event.addListener(_11,"click",this.cancelEdit,this,true);},updateValue:function(e){var el=YAHOO.util.Event.getTarget(e);YAHOO.util.Event.stopEvent(e);Widgets.EditInPlace.li.start();var _14=el.id.replace(/(.*)_(save|textarea)/i,"$1");var _15=_14+"_textarea";var _16=YAHOO.util.Dom.get(_15);var _17=_16.value;var _18=Kore.getDocumentCharset();var _19=_18.toLowerCase()=="iso-8859-1"?escape:encodeURIComponent;var _1a=_19(_17);var _1b=this;window[this.id+"_updateValue"](this.pk,"POST-DATA","edit_value="+_1a,function(_1c,_1d){Widgets.EditInPlace.li.stop();var _1e=_1d[0];if(_1e.error){alert("Error no: "+_1e.error.code+" has occured: \""+_1e.error.message+"\" while executing query to URL: \""+_1e.URL+"\".");}else{if(_1e.content.error){alert("Error: "+_1e.content.error.message);}else{var _1f=_1e.content;if(_1f=="OK"){var _20=YAHOO.util.Dom.get(_14);if(_17==""){_17=_1b.options.empty;}
_20.innerHTML=_17;_1b.cleanup(_14);}}}});},cancelEdit:function(e){var el=YAHOO.util.Event.getTarget(e);YAHOO.util.Event.stopEvent(e);var _23=el.id.replace(/(.*)_cancel/i,"$1");this.cleanup(_23);},cleanup:function(_24){var _25=YAHOO.util.Dom.get(_24);var _26=YAHOO.util.Dom.get(_24+"_editor");if(_26){_26.parentNode.removeChild(_26);this.showAsEditable(_25,false);_25.style.display="block";Widgets.EditInPlace.currentEditElement[this.id]="";}}};