<?php
$res = array(
'PHP_FILE_READ_ERROR' => 'File Error. Internal Error.',
'PHP_FILE_WRITE_ERROR' => 'File Error. Internal Error.',
'PHP_FILE_CREATE_ERROR' => 'File Error. Internal Error.',
'PHP_FILE_DELETE_ERROR' => 'File Error. Internal Error.',
'PHP_FILE_FOLDER_ERROR' => 'File Error: %s %s.',
'PHP_FILE_CHECK_FOLDER_ERROR' => 'File Error: %s. Internal Error.',
'PHP_FILE_READ_ERROR_D' => 'File Error. Reading File: %s.',
'PHP_FILE_WRITE_ERROR_D' => 'File Error. Writing content to file: %s.',
'PHP_FILE_CREATE_ERROR_D' => 'File Error. Creating File: %s.',
'PHP_FILE_DELETE_ERROR_D' => 'File Error. Deleting File: %s.',
'PHP_FILE_FOLDER_ERROR_D' => 'File Error: %s %s.',
'PHP_FILE_CHECK_FOLDER_ERROR_D' => 'File Error: %s. No %s permissions in %s folder.',
'PHP_FILE_RENAME_NO_FILE' => 'File Error. Internal Error.',
'PHP_FILE_RENAME_NO_FILE_D' => 'File Error. File source missing: %s.',
'PHP_FILE_RENAME_EXISTS' => 'File Error. Internal Error.',
'PHP_FILE_RENAME_EXISTS_D' => 'File Error. File destination already exists: %s.',
'PHP_FILE_RENAME' => 'File Error. Internal Error.',
'PHP_FILE_RENAME_D' => 'File Error. Error renaming file \'%s\' to \'%s\'.',
'PHP_FILE_COPY_NO_FILE' => 'File Error. Internal Error.',
'PHP_FILE_COPY_NO_FILE_D' => 'File Error. File source missing: %s.',
'PHP_FILE_COPY_EXISTS' => 'File Error. Internal Error.',
'PHP_FILE_COPY_EXISTS_D' => 'File Error. File destination already exists: %s.',
'PHP_FILE_COPY' => 'File Error. Internal Error.',
'PHP_FILE_COPY_D' => 'File Error. Error copying file \'%s\' to \'%s\'.',
);
?>